### ISSUE TITLE
Cannot run into production mode

### ISSUE THREAD

**Issue by joanfont** [decidim/docker#111]
Trying to run `decidim/decidim:0.29.0` in production mode it fails when initializing seeds:

Here is my `docker-compose.yml`:

```yml
services:
  decidim:
    image: decidim/decidim:0.29.0
    entrypoint: ["/code/vendor/hello-world.sh"]
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    ports:
      - 3000:3000
    volumes:
      - ./scripts:/code/vendor
      - decidim-uploads:/code/public/uploads
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://decidim:decidim@postgres:5432/decidim
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    depends_on:
      - postgres
      - redis
  postgres:
    image: library/postgres:17.4-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=decidim
      - POSTGRES_DB=decidim
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: library/redis:7.4-alpine
    volumes:
      - redis-data:/data
volumes:
  decidim-uploads: {}
  pg-data: {}
  redis-data: {}
 ```
